### ISSUE TITLE
mkdir is not in /usr/bin but in /bin

### ISSUE THREAD

**Issue by vervaekejonathan** [l0b0/fgit#4]
When running sudo make install I get the following error:

> /usr/bin/mkdir /usr/local/share/fgit
> make:
> /usr/bin/mkdir: Command not found
> Makefile:38: recipe for target '/usr/local/share/fgit' failed
> make: *** [/usr/local/share/fgit] Error 127

whereis mkdir tells me /bin/mkdir and not /usr/bin/mkdir

(i use ubuntu 16.10)

**Comment by l0b0** [comment]
Linux distros put tools like `mkdir` in different directories - In Arch Linux `/bin` is a symlink to `/usr/bin`, so everything is by default referenced in `/usr/bin`. To work around this you can specify where individual tools are, for example `sudo make MKDIR=/bin/mkdir install`.
